// Technical module content for the Neoteric GET Handbook.
// Each module: id, title, days (when taught), why, know[], do[], drill, mistakes[], check[]

module.exports = [
{
  id: "M01", title: "Site Safety & EHS", days: "D01, reinforced daily",
  why: "Every other module in this handbook is worthless if someone is injured learning it. Safety is not a topic you complete on Day 1 — it is the condition under which all your other work is allowed to happen. As a trainee you are the least experienced person on site and statistically the most at risk.",
  know: [
    "The five site hazards that cause almost all serious construction injuries in India: fall from height, fall of material, electrocution, excavation collapse, and struck-by moving plant.",
    "Mandatory PPE and when each item applies: safety helmet (always, inside the barricade line), safety shoes (always), full-body harness with double lanyard (any work above 1.8 m without edge protection), high-visibility jacket, gloves for handling steel and shuttering, goggles and face shield for cutting, grinding and welding, ear protection near breakers and DG sets.",
    "Scaffolding basics: base plates on firm ground, no brick or wooden packing under standards, full boarding, toe boards, guard rails at 1 m and mid-rail, ladders tied and extending 1 m above the landing, and a scaffold tag (green/red) that says whether it may be used.",
    "Excavation: any excavation deeper than 1.5 m needs shoring, benching or a stable slope; spoil kept at least 1 m from the edge; a ladder every 15 m of trench length; hard barricading around every open pit.",
    "Electrical: no bare joints, no wire in a socket without a plug top, every temporary board with an ELCB/RCCB, DG and welding machine earthed, and lockout-tagout before working on any panel.",
    "Lifting: tower crane and hoist operators must be certified; nobody stands under a suspended load; tag lines used to control swing; slings and shackles inspected and colour-coded.",
    "Hot work permit for welding and gas cutting, fire extinguisher within 5 m, fire watch for 30 minutes after work stops.",
    "Emergency response: assembly point location, first-aid room, ambulance contact, nearest hospital, and the site's emergency number — you must know these on Day 1, not look them up later.",
  ],
  do: [
    "Conduct a toolbox talk to a gang of 10 workers, in Hindi, on a single hazard, in under 5 minutes.",
    "Inspect a scaffold against a checklist and issue a red tag if it fails.",
    "Fill and close a work-at-height permit and a hot work permit.",
    "Identify and stop an unsafe act using Stop-Work Authority (Module 19), and write the entry afterwards.",
  ],
  drill: "Walk the whole site with the Safety Officer and photograph ten unsafe conditions. For each, write the hazard, who could be hurt, and the one control that fixes it. Present to the batch the same evening.",
  mistakes: [
    "Wearing a helmet without fastening the chin strap — in a fall it comes off before it protects you.",
    "Hooking a harness lanyard to the same pipe you are standing on, or to a scaffold that is itself not anchored.",
    "Assuming a worker who nods has understood. Ask him to repeat the instruction back.",
    "Treating safety as the Safety Officer's job. Safety is line responsibility — it is yours.",
  ],
  check: [
    "At what height does fall protection become mandatory on our sites, and what is the exception?",
    "Where is the assembly point at your site and what is the emergency contact number?",
    "Your contractor says the harness slows his men down and the work is only for 20 minutes. What do you do, and what do you write?",
  ],
},
{
  id: "M02", title: "Reading Drawings",
  days: "D02–D03",
  why: "A site engineer's core function is converting a two-dimensional drawing into a three-dimensional structure without error. Almost every expensive site mistake — a misplaced shear wall, a shaft that does not align, a beam that clashes with a duct — is a drawing-reading failure, not a construction failure. This is the single highest-value skill in your first month.",
  know: [
    "The drawing set and who issues it: architectural (GFC plans, sections, elevations, door-window schedule, toilet and kitchen details), structural (foundation layout, column layout and schedule, beam layout, slab reinforcement, BBS), MEP (plumbing, firefighting, electrical, HVAC), and landscape/external development.",
    "Title block discipline: drawing number, revision number, date, 'Good For Construction' stamp, scale, and the revision cloud. A drawing without a current GFC stamp must not be built from — full stop.",
    "Grid lines and how everything on site is located from them: alphabetical in one direction, numerical in the other; every column, wall and opening is dimensioned from a grid, never from another wall.",
    "Levels on drawings: FFL (finished floor level), SFL (structural floor level, usually FFL minus the floor finish thickness), plinth level, and the site datum / temporary benchmark that all of them are measured from.",
    "Scale and how to read a dimension: always trust the written dimension over the scaled measurement. Never scale off a drawing to build.",
    "Standard symbols and abbreviations: section marks, detail bubbles, hatching for brickwork, concrete, earth and insulation; door/window tags; north point.",
    "Structural drawing conventions: column schedule (size, reinforcement, lap zones, floor-wise change), beam mark and its section, slab bottom and top steel with distribution steel, development length Ld and lap length, cover.",
    "Bar Bending Schedule: bar mark, diameter, shape code, cut length, number of bars, weight. How the cut length differs from the centre-line length because of bends and hooks.",
    "Clash checking: overlaying the architectural, structural and MEP drawings for the same area before starting work — the cheapest hour you will ever spend.",
  ],
  do: [
    "Given a GFC set for one floor, mark up the column layout on site with grid lines and confirm every column position against two grid dimensions.",
    "Read a column schedule and state the reinforcement, tie spacing and cover for a named column at a named floor.",
    "Read a slab reinforcement drawing and independently list the bars, spacing and extra top steel needed for one panel.",
    "Take a drawing register and confirm that the print in the site office is the latest revision.",
  ],
  drill: "Take one flat's architectural plan and the corresponding structural and plumbing drawings. Overlay them. Find and report at least three points where a beam, a shaft, a drop or a sunk conflicts with the architectural intent. Present your findings with drawing references.",
  mistakes: [
    "Building from a superseded revision because the latest print was never pulled from the site office.",
    "Confusing FFL with SFL and casting the slab at the wrong level, so the tiling thickness no longer fits.",
    "Measuring a column position from the adjacent brick wall instead of the grid line, and propagating the error up the building.",
    "Ignoring the note block. Notes on a structural drawing carry as much authority as the drawing itself.",
  ],
  check: [
    "What is the difference between FFL and SFL, and where do you find the difference?",
    "A drawing shows a dimension of 3200 but scaling it gives 3350. Which do you follow and why?",
    "How do you confirm that the drawing in your hand is the one you are allowed to build from?",
  ],
},
{
  id: "M03", title: "Measurement, Mensuration & the Measurement Book",
  days: "D04",
  why: "Everything on a construction site is eventually paid for by measurement. If you cannot measure accurately and record it in a form that survives audit, you cannot certify a contractor's bill, you cannot control material, and you cannot prove what was built. Measurement is where engineering meets money.",
  know: [
    "Units used on site and their conversions: metre, millimetre, square metre, cubic metre, quintal, metric tonne, running metre, number. Local units (square feet, brass, bori) and their exact conversion — 1 brass = 100 cft = 2.83 m³; 1 bag of cement = 50 kg; 1 m³ = 35.31 cft.",
    "Mensuration you will use daily: area of rectangle, triangle, trapezium, circle; volume of cuboid, cylinder, frustum; surface area for plaster and painting; weight of steel = d²/162 kg per metre.",
    "IS 1200 — the mode of measurement. It is the rulebook that decides what is measured, in what unit, what is deducted and what is not. Different parts cover earthwork, concrete, masonry, plaster and finishing.",
    "Standard deduction rules that cause the most disputes: openings in masonry and plaster, deduction for beams and columns in wall measurement, no deduction for openings below a stated area, and how sunk portions and drops are treated.",
    "The Measurement Book (MB): a legal document. Written in ink, no erasure, corrections struck through once and initialled, every page signed by the recorder and the checker, and cross-referenced to the bill it feeds.",
    "Level-based measurement for earthwork: the grid level method, original ground level versus formation level, and how the average depth is computed.",
    "Abstract of measurement: how the MB entries roll up into quantities against BOQ item numbers.",
  ],
  do: [
    "Measure and record a completed brick wall with openings, applying IS 1200 deductions correctly.",
    "Record an MB entry from scratch for one item, get it checked, and correct it in the proper form.",
    "Compute the steel weight of a full BBS sheet by hand and cross-check against the stores issue record.",
    "Compute earthwork quantity for an excavated footing from grid levels.",
  ],
  drill: "Take one completed flat. Measure every item that would appear in a contractor's bill — masonry, plaster, tiling, doors, windows, painting. Prepare the abstract. Compare your quantity against the last certified bill for that flat. Explain every difference.",
  mistakes: [
    "Measuring what is drawn instead of what is built. You measure executed work only.",
    "Forgetting deductions for openings, then trying to recover the money after payment has been released.",
    "Recording in a rough notebook and copying into the MB later. The MB entry must be made at the point of measurement.",
    "Using square feet in one place and square metres in another within the same abstract.",
  ],
  check: [
    "What is the weight per metre of a 16 mm bar, and how did you derive it?",
    "Is an opening of 0.4 m² deducted from plaster? What decides the answer?",
    "You find an arithmetic error in a signed MB page. What is the correct way to fix it?",
  ],
},
{
  id: "M04", title: "Land Survey & Setting Out",
  days: "D05",
  why: "Setting out is the one activity where an error cannot be corrected later. A building set out 300 mm off its boundary is a legal problem, a setback violation and potentially a demolition. Everything else on site can be redone; the position of the building cannot.",
  know: [
    "The instruments: chain/tape, ranging rods, plumb bob, line dori, optical square, theodolite, total station, and where each is appropriate.",
    "Total station fundamentals: setting up and centring over a point, levelling, backsight orientation, coordinate system, occupying a station, stake-out (setting out) mode, and recording the instrument log.",
    "Site datum and control: the permanent benchmark, temporary benchmarks, control pillars, and why they must be protected and re-verified periodically.",
    "Reading a site plan against the approved layout: plot boundary, setbacks, FSI/ground coverage line, road centre line, and the building line.",
    "Setting out a building: establishing the base line, setting the grid, offsetting the centre lines, fixing profiles/batter boards clear of the excavation, and marking column centres.",
    "The 3-4-5 rule for checking a right angle without an instrument, and diagonal checking of a rectangle — if the diagonals are equal, the rectangle is true.",
    "Chainage, offsets and how a road or drain alignment is set out and checked.",
    "Verification: every setting out must be independently checked by a second person before excavation, and signed off.",
  ],
  do: [
    "Set up and centre a total station over a control point and orient it to a backsight, unassisted.",
    "Set out the grid for one building block and mark column centres to within the project tolerance.",
    "Establish a temporary benchmark from the site datum and record it.",
    "Check a set-out rectangle by diagonals and by the 3-4-5 method.",
  ],
  drill: "Set out a 4-column bay independently. Have another trainee check it independently. Compare the two results and account for every millimetre of difference. Then have the Site Engineer check both.",
  mistakes: [
    "Setting profiles inside the excavation zone, so they are destroyed the moment the JCB starts.",
    "Taking the backsight to a point that has itself moved.",
    "Setting out from the boundary wall instead of the surveyed boundary — boundary walls are rarely where the deed says they are.",
    "Not recording the setting-out data, so when a dispute arises there is nothing to defend.",
  ],
  check: [
    "How do you check a right angle on site without any instrument?",
    "What is a temporary benchmark and why do we need more than one?",
    "Excavation has started and someone has knocked out a profile peg. How do you recover the line?",
  ],
},
{
  id: "M05", title: "Levels & Levelling",
  days: "D06",
  why: "Level errors are invisible until finishing, and then they are extremely expensive. A slab cast 25 mm low means either a thicker screed on every square metre of that floor or a door that will not open. Levels are how a building stays consistent from foundation to terrace.",
  know: [
    "Instruments: dumpy level, auto level, laser level, water level (pipe level) and when each is used. Staff reading to the nearest millimetre.",
    "The vocabulary: benchmark (BM), reduced level (RL), height of instrument (HI), backsight (BS), intermediate sight (IS), foresight (FS), change point, and the temporary adjustments of a level.",
    "Height of Instrument method: HI = RL of BM + BS. RL of any point = HI − staff reading at that point.",
    "Rise and Fall method, and when it is preferred (it checks every intermediate point, HI method does not).",
    "The arithmetic check: ΣBS − ΣFS = Last RL − First RL. Every level book page must close. If it does not, the page is wrong — do not adjust it to fit.",
    "Fly levelling and closing back to the benchmark. Permissible closing error and how it is distributed.",
    "Practical level control on a building: transferring level from floor to floor, the 1-metre level line marked on every column at each floor, and why every finishing trade works from that one line.",
    "Slopes and falls: terrace and toilet slopes, drain invert levels, ramp gradients, road camber — expressed as 1:X or as a percentage.",
  ],
  do: [
    "Set up an auto level, take a full round of readings, book them in a level field book and close the arithmetic check.",
    "Transfer a level from the ground floor to the fifth floor and prove it against an independent transfer.",
    "Mark the 1-metre line on every column of one floor and have it verified.",
    "Check the fall in a cast toilet sunk and confirm it drains to the trap.",
  ],
  drill: "Take levels on a freshly cast slab at a 3 m × 3 m grid. Produce a level contour sheet showing high and low spots against the design SFL. Report to the Site Engineer with the maximum deviation and where the screed thickness will have to change.",
  mistakes: [
    "Booking a change point as an intermediate sight. The level book will not close and you will not know why.",
    "Adjusting readings to make the check close. This is falsification, and it is treated as such (see Module 19).",
    "Working from a benchmark that was disturbed by site traffic.",
    "Assuming the slab is level because the shuttering was level — deflection and concrete placement change everything.",
  ],
  check: [
    "Write the HI method formula and explain each term.",
    "Your level book page does not close by 14 mm. What are the three most likely reasons?",
    "What is the 1-metre line and which trades depend on it?",
  ],
},
{
  id: "M06", title: "Cement & Cement Testing",
  days: "D07",
  why: "Cement is the most expensive ingredient per unit weight in ordinary concrete and the one whose deterioration is easiest to miss. Cement that has absorbed moisture in the store looks almost normal but has lost strength permanently. Your inspection at the gate and in the godown is the last defence.",
  know: [
    "Types and where used: OPC 43, OPC 53, PPC (fly ash blended), PSC (slag blended), and white cement. PPC gains strength slower but is more durable and generates less heat — check what the project specification allows before accepting any substitution.",
    "What arrives with the cement: the test certificate (manufacturer's), batch/lot number, week and year of manufacture printed on the bag, and the ISI mark. Cement older than three months from manufacture must be retested before use.",
    "Field tests you perform at the gate, in minutes, without a laboratory: (1) colour — uniform greenish grey, (2) lump test — no hard lumps that do not crush between fingers, (3) float test — a pinch thrown on water should float briefly before sinking, (4) hand insertion — thrusting your hand into the bag should feel cool, not warm, (5) smell — no earthy smell, (6) glass plate/setting test — a thick paste pat on a glass plate kept under water should set without cracking within 24 hours.",
    "Laboratory tests and their IS references: fineness by sieving or Blaine (IS 4031 Part 1 / Part 2), standard consistency by Vicat, initial and final setting time (IS 4031 Part 5), soundness by Le Chatelier (IS 4031 Part 3), and compressive strength on 70.6 mm mortar cubes (IS 4031 Part 6).",
    "Indicative acceptance values to know by heart — always confirm against the current IS code and the project specification: initial setting time not less than 30 minutes, final setting time not more than 600 minutes, Le Chatelier expansion not more than 10 mm.",
    "Storage rules that protect the material: stacked on a raised wooden platform at least 150–200 mm off the floor, at least 300 mm clear of walls, not more than 10 bags high, covered, with clear FIFO marking so the oldest stack is issued first.",
    "Consumption control: theoretical cement consumption per m³ of each concrete grade and per m² of each plaster and masonry item, compared monthly against actual issue. A widening gap is either wastage, theft, or over-rich mixes.",
  ],
  do: [
    "Inspect an incoming cement truck: verify grade, brand, manufacture date, bag count, bag weight by random sampling, and the test certificate — then accept or reject in writing.",
    "Perform all six field tests and record the result.",
    "Draw a cement sample correctly for laboratory testing and prepare the sample identification label.",
    "Audit a cement godown for stacking height, plinth clearance, wall clearance, FIFO and cover.",
  ],
  drill: "Take one month of cement issue records from the store for one building. Compute the theoretical consumption from the work actually executed in that month. Present the variance and your explanation for it.",
  mistakes: [
    "Accepting a truck because the driver is waiting and the paperwork 'will come later'. Once it is unloaded, your leverage is gone.",
    "Stacking new bags on top of old ones, which guarantees the old cement is never issued.",
    "Checking the bag count but not the bag weight. Short weight on 500 bags is a large loss and is invisible unless you weigh.",
    "Using cement that has been stored through a monsoon without retesting.",
  ],
  check: [
    "Name three field tests for cement and what each one tells you.",
    "What is the maximum stack height for cement bags and why does it matter?",
    "A consignment has no manufacture date visible on the bags. What do you do?",
  ],
},
{
  id: "M07", title: "Concrete & Concrete Testing",
  days: "D08",
  why: "Concrete is the only material on site that is manufactured at the moment of use and cannot be inspected before it is committed. Once it is in the shutter, every defect is permanent and every remedy is expensive. Concrete quality is decided in the thirty minutes before the pour, not after.",
  know: [
    "Ingredients and their control: cement, fine aggregate, coarse aggregate, water and admixture. Aggregate grading, flakiness, silt content in sand (field silt test — confirm the permitted limit against IS 383 and the project specification), and the effect of moisture in aggregate on the actual water-cement ratio.",
    "Nominal mix versus design mix. Grades M10, M15, M20, M25, M30 and above. Above M20, IS 456 requires a design mix — a nominal mix is not acceptable for structural work.",
    "The water-cement ratio is the single strongest determinant of strength. Every extra litre of water added at site to make placing easier is a direct, permanent loss of strength.",
    "Batching: weigh batching versus volume batching, the correction for bulking of sand, and why volume batching is not acceptable for design mixes.",
    "Slump test (IS 1199): the cone dimensions, three-layer filling with 25 tamps each, lifting the cone in 5–10 seconds, and measuring the subsidence. Indicative ranges — lightly reinforced sections 25–75 mm, heavily reinforced 75–100 mm, pumped concrete typically 100–150 mm. The specified slump comes from the mix design, not from the contractor's preference.",
    "Cube test (IS 516): 150 mm cubes, one sample = three cubes, tested at 7 and 28 days. Sampling frequency from IS 456 Table 11 — 1 to 5 m³ one sample, 6 to 15 m³ two, 16 to 30 m³ three, 31 to 50 m³ four, and one additional sample for each further 50 m³ or part thereof.",
    "Acceptance criteria (IS 456 Clause 16) and what to do when a cube fails: retest, core test (IS 516), non-destructive testing by rebound hammer and ultrasonic pulse velocity (IS 13311), and load testing as the last resort. A failing cube result is an NCR, not a conversation.",
    "Placing: free fall limited (typically 1.5 m), no segregation, layer thickness matched to vibrator length, needle vibrator held vertical and withdrawn slowly, no vibrating through reinforcement, and the maximum time from batching to placing.",
    "Construction joints: where they are permitted, how the surface is prepared (laitance removed, roughened, cleaned, wetted), and slurry/bonding agent application.",
    "Curing: minimum 7 days for OPC concrete and longer for blended cements; ponding, wet hessian, curing compound; and why the first 24 hours matter most.",
    "Ready-mix concrete: the batch slip, the time stamp, the drum revolution count, temperature, and the rule that water is never added at site to an RMC truck.",
    "Cover and its enforcement: cover blocks of the correct grade and thickness, adequate number, and the environmental exposure table in IS 456 that decides the required cover.",
  ],
  do: [
    "Run a complete pre-pour checklist and sign it: shuttering, reinforcement, cover, cleanliness, embedded items, level marks, access, vibrators with standby, curing arrangement, lighting, and weather.",
    "Perform a slump test and cast a set of three cubes correctly, including identification marking and curing.",
    "Read an RMC batch slip and identify a non-conformance in it.",
    "Interpret a 7-day and 28-day cube report against the acceptance criteria.",
  ],
  drill: "Attend a full pour from batching to curing. Record the timeline: batch time, arrival, slump, placement start and finish, number of cubes cast, vibrator failures, and the time curing started. Present what you would change about how the pour was run.",
  mistakes: [
    "Allowing water to be added to improve workability. This is the most common and most damaging site practice in India.",
    "Casting cubes from a convenient part of the load instead of a random sample, which makes the entire test meaningless.",
    "Vibrating until the surface looks smooth — that is over-vibration and it segregates the mix.",
    "Starting curing the next morning. Curing starts as soon as the surface can take it without damage.",
    "Treating a failed 7-day cube as 'wait for 28 days'. Raise the NCR at 7 days and start investigating.",
  ],
  check: [
    "How many cubes would you cast for a 42 m³ pour, and why?",
    "The pump operator asks for two more buckets of water. Give your answer and your reasoning.",
    "A 28-day cube result is 21.5 N/mm² for M25. What happens next?",
  ],
},
{
  id: "M08", title: "Reinforcement Steel & Bar Bending Schedule",
  days: "D08 (with concrete)",
  why: "Steel is typically the second-largest material cost on a project and the one with the highest theft and wastage exposure. It is also the element whose errors are sealed inside concrete forever. Nobody can inspect a lap length after the pour.",
  know: [
    "Grades and standards: Fe415, Fe500, Fe500D, Fe550 and their CRS/TMT variants under IS 1786. What the 'D' means and why the structural consultant specifies it.",
    "Acceptance at gate: manufacturer's test certificate, brand rolling marks on the bar, bundle tags, diameter check by vernier, and the mass-per-metre check — the strongest practical test for under-weight steel. Nominal mass = d²/162 kg/m; tolerance on mass is specified in IS 1786 by diameter.",
    "Laboratory tests: tensile strength, yield stress, percentage elongation, and the rebend test. Sampling frequency per lot as specified.",
    "Storage: off the ground on sleepers, sorted by diameter, tagged, covered, and never in contact with standing water or earth.",
    "Cutting and bending: standard bend and hook allowances, shape codes, cut length versus centre-line length, and the bending tolerance.",
    "Development length (Ld), lap length, and lap location: laps staggered, laps in the zone of least stress, no lap in a zone the consultant has prohibited, and the percentage of bars that may be lapped at one section.",
    "Placement discipline: cover blocks (grade, size, number per m²), chairs and spacers between top and bottom mesh, binding wire pattern, and the rule that no bar may be moved to make way for a conduit without the consultant's approval.",
    "Congestion and clashes at beam-column junctions, and why they must be resolved on paper before the steel is fixed.",
    "Cutting waste control: bar-cutting optimisation, target wastage percentage (typically 2–5% depending on the item), and reconciliation of steel received against steel fixed plus scrap returned.",
  ],
  do: [
    "Verify a steel consignment: rolling marks, diameter, mass per metre, tag and test certificate. Accept or reject in writing.",
    "Prepare a BBS for one beam from the structural drawing and compute the total weight.",
    "Inspect fixed reinforcement for one slab panel against the drawing: diameter, spacing, extra top steel, cover, chairs, laps.",
    "Perform a steel reconciliation for one floor.",
  ],
  drill: "Check the reinforcement of a slab that is ready for pouring, before the Site Engineer does. List every deviation you find. Compare your list against his. The difference between the two lists is your learning for the day.",
  mistakes: [
    "Counting bars but not measuring spacing at mid-span, where the fixers most often drift.",
    "Accepting cover blocks made of weak mortar that crush under the fixer's foot.",
    "Allowing an electrician to cut or displace a bar for a conduit.",
    "Signing the reinforcement checklist while standing at the edge of the slab. You must walk every panel.",
  ],
  check: [
    "What is the nominal mass per metre of a 12 mm bar and how would you verify a consignment against it?",
    "Why are laps staggered, and what limits the percentage lapped at one section?",
    "A fixer has provided cover blocks only along the edges of a slab. What is wrong and what do you instruct?",
  ],
},
{
  id: "M09", title: "Shuttering & Formwork",
  days: "D09",
  why: "Formwork determines the shape, the line, the level and the finish of every concrete element, and it is where most site accidents and most concrete rejections originate. It is also 10–15% of the concrete cost. A good shuttering carpenter saves you money twice — once in concrete and once in plaster.",
  know: [
    "Systems in use: traditional timber and ply, steel plate shuttering, aluminium (Mivan/Alform) system formwork, tunnel form, and table form. What each is suited to and what each demands from the site team.",
    "Components and their function: sheeting/plate, joists and runners, props and telescopic spans, sole plates, wedges, clamps, tie rods, walers, spacers and cones.",
    "Design considerations you must understand even if you do not design it: concrete pressure on vertical forms increases with pour rate and decreases with temperature; props must be plumb, on firm ground, on a sole plate, and continuous through floors (back-propping).",
    "Setting and checking: line, level, plumb, diagonal, camber where specified, joint tightness against grout leakage, cleanliness of the inside face, and shuttering oil applied before the reinforcement is placed — never after.",
    "Deshuttering periods (IS 456, Clause 11.3) — indicative, and always subject to the consultant's instruction and to concrete strength gain: vertical faces of walls, columns and beam sides 16 to 24 hours; soffit of slabs with props left under 3 days; soffit of beams with props left under 7 days; props to slabs spanning up to 4.5 m 7 days and over 4.5 m 14 days; props to beams spanning up to 6 m 14 days and over 6 m 21 days.",
    "Back-propping and re-propping: why the floor below and often two floors below must stay propped while a new floor is cast, and why removing props early is one of the leading causes of collapse.",
    "Tolerances: verticality of columns, deviation in cross-section, level of slab soffit, and the line of a wall — know the project's stated tolerance before you accept the shuttering.",
    "Repetition and cost: number of repetitions expected from ply, steel and aluminium; the cost of handling and cleaning; and how the shuttering cycle time drives the whole project schedule.",
  ],
  do: [
    "Check shuttering for one column: plumb in two directions, cross-section, alignment to grid, tie condition, joint tightness, and cleanliness. Sign the checklist.",
    "Check slab shuttering: soffit level across the panel, prop spacing, sole plates, back-propping, edge shutters and openings.",
    "Instruct and supervise deshuttering of a column, ensuring no edge damage.",
    "Prepare a shuttering cycle plan for one floor and identify the critical constraint.",
  ],
  drill: "Measure the soffit level of a slab shutter at a 3 m grid before pouring and again after pouring. Report the deflection. Explain what this means for the finished floor level and the screed.",
  mistakes: [
    "Applying shuttering oil after the reinforcement is placed, which coats the bars and destroys bond.",
    "Props resting directly on loose soil or on a brick.",
    "Removing props on the strength of the calendar instead of on strength gain, particularly in winter or with blended cements.",
    "Reusing plywood past its life so the concrete face needs heavy plaster to correct.",
  ],
  check: [
    "State the deshuttering period for the soffit of a beam with props left under, and the code reference.",
    "What is back-propping and why is it required?",
    "Shuttering oil has been applied and then the crew found a bar was missing. What is the correct sequence to recover?",
  ],
},
{
  id: "M10", title: "Brick, Block & Masonry Machinery",
  days: "D09",
  why: "Masonry sets the geometry of every room a customer will ever stand in. It is also the trade with the widest quality variation between one gang and the next. Machinery — block-making plants, cutting machines, mortar mixers and mechanised hoists — changes the economics but not the standards.",
  know: [
    "Materials: burnt clay bricks (IS 1077), fly ash bricks (IS 12894), concrete blocks and AAC blocks (IS 2185). For common burnt clay bricks the minimum compressive strength is 3.5 N/mm² for the lowest class; water absorption and efflorescence limits are specified by class. Confirm the class and the values against the current code and the project specification.",
    "Acceptance testing: dimension check on a stack of 20 bricks laid end to end, compressive strength, water absorption (24-hour immersion), efflorescence, and visual soundness — a good brick rings when struck and does not break when dropped from about one metre.",
    "AAC and concrete blocks: dry density, dimensional tolerance, the requirement for block-jointing mortar or thin-bed adhesive rather than ordinary cement mortar, and their much higher sensitivity to moisture at the time of laying.",
    "Mortar: the specified mix (commonly 1:4 or 1:6 depending on the wall), machine mixing, consumption within the initial setting time, and the ban on re-tempering set mortar with more water.",
    "Laying discipline: bricks soaked adequately before laying (clay bricks) and blocks NOT soaked but only surface-wetted; joint thickness typically 10 mm and uniform; frog upward; proper bond with no vertical joint continuing through courses; maximum height raised in a day generally limited to about 1.0–1.5 m; and racking back rather than toothing at junctions.",
    "Interface with the structure: the gap at the underside of the beam or slab left for at least 7 days and then closed with a wedged course or non-shrink grout; chicken mesh or fibre mesh at every RCC-to-masonry junction, typically 150 mm on each side; and holdfasts and lintels over openings.",
    "Machinery: block-making machine operation and curing yard management, table saw and block cutter for clean cutting instead of hammer breaking, mechanised mortar mixers, and material hoists. Every machine has a safety interlock and an operator competency requirement.",
    "Wastage control: breakage in transit and handling, wastage percentage targets, and cutting waste reduced by planning course heights against the floor-to-floor height.",
  ],
  do: [
    "Test a brick consignment: dimension check on 20, water absorption, visual and ring test. Accept or reject.",
    "Check a wall under construction for plumb, line, joint thickness, bond and height raised in the day.",
    "Set out a wall from the grid and mark the openings before the gang starts.",
    "Supervise a block cutting operation and enforce the machine's safety requirements.",
  ],
  drill: "Take a completed but unplastered floor. Check every wall for plumb and every room for its diagonal. Mark deviations on the plan. Compute how much extra plaster thickness the deviations will cost, in m³ and in rupees.",
  mistakes: [
    "Soaking AAC blocks like clay bricks, which causes shrinkage cracking after plaster.",
    "Closing the gap below the beam the same day, so the wall carries load it was never designed for and cracks.",
    "Skipping chicken mesh at junctions, which produces the single most common customer complaint after handover.",
    "Raising a wall more than 1.5 m in a day and losing plumb.",
  ],
  check: [
    "How much of a wall may be raised in one day, and what happens if you exceed it?",
    "Why is chicken mesh needed at an RCC-to-masonry junction, and what width on each side?",
    "How do you check the dimensional consistency of a brick consignment?",
  ],
},
{
  id: "M11", title: "Plastering",
  days: "Supervision immersion",
  why: "Plaster is the surface the customer sees, the base every finish depends on, and the item most likely to be redone at your cost. It also consumes enormous quantities of cement and sand, so plaster thickness control is direct margin control.",
  know: [
    "Preparation: surface cleaned of dust and oil, RCC surfaces hacked to give a key, joints raked in masonry, surface thoroughly wetted the previous evening and again before starting, and all conduits, boxes and chases closed and cured before plastering.",
    "Thickness and coats: internal plaster typically 12 mm in a single coat; external typically 15–20 mm in two coats (a rough base coat and a finishing coat) with the base coat allowed to cure before the second; ceiling plaster typically 6 mm. Confirm against the project specification.",
    "Mortar mix as specified, machine mixed, and used within its setting time.",
    "Level control: gauge/thappi dots and screed bands fixed to a plumb line and to the 1-metre level line before plastering starts. Plastering without dots is guesswork and is the reason walls end up 30 mm thick in one corner and 8 mm in another.",
    "Corners, bands and grooves: metal or PVC corner beads, drip moulds on external projections, and grooves at material changes to control cracking.",
    "Curing: continuous wet curing for at least 7 days, starting about 24 hours after application.",
    "Common defects and their causes: hollowness (poor bond or dry substrate), cracking (rich mix, excess thickness in one coat, poor curing), efflorescence, uneven surface, and blistering.",
    "Quality checks: straight edge and spirit level over 2 m, hollowness by tapping the entire surface with a wooden mallet, verticality by plumb, and room diagonals.",
    "Quantity control: theoretical mortar consumption per m² at each thickness, compared to actual issue. Over-consumption points to over-thickness, which points to bad masonry.",
  ],
  do: [
    "Fix dots and screeds for one room to plumb and level, and get them checked before plaster starts.",
    "Inspect completed plaster: hollowness by tapping the full area, straight edge, plumb, and corner squareness. Record the defects on a room-wise sheet.",
    "Compute the plaster quantity for one flat and reconcile against material issued.",
    "Supervise curing and record it.",
  ],
  drill: "Tap-test every plastered wall in one flat. Mark hollow areas with chalk. Photograph and measure the total hollow area as a percentage. Present the cause analysis and the rectification instruction to the contractor.",
  mistakes: [
    "Plastering on a dry substrate, which pulls water out of the mortar and guarantees hollowness.",
    "Correcting bad masonry with thick plaster instead of correcting the masonry.",
    "Plastering over unfilled chases, so the plaster cracks along every conduit line within months.",
    "Stopping curing after two days because the surface 'looks fine'.",
  ],
  check: [
    "Why is hacking needed on RCC surfaces before plaster?",
    "What is the purpose of a dot and screed, and when are they fixed?",
    "You find 12% of a wall hollow on tapping. What is your instruction and what is the likely cause?",
  ],
},
{
  id: "M12", title: "Waterproofing",
  days: "Quality immersion",
  why: "Waterproofing is not on your original syllabus, and it should be. Water ingress is the number one source of post-handover complaints, legal disputes and reputational damage in Indian residential real estate. It is also almost impossible to rectify after finishing is complete.",
  know: [
    "Where waterproofing is required: footings and retaining walls in contact with earth, basement raft and walls, terrace and roof slabs, toilets and bathrooms, kitchens and utility areas, balconies, planter boxes, water tanks and sumps, and every external wall in a high-rainfall exposure.",
    "Systems and where each applies: integral waterproofing compounds in concrete, crystalline waterproofing, cementitious polymer coating, APP/SBS modified bitumen membrane, liquid-applied polyurethane, brickbat coba with china mosaic, and injection grouting for remedial work.",
    "Sequence discipline: waterproofing is applied to a cured, clean, sound, correctly sloped substrate; every penetration (plumbing, conduit, drain) must be complete and sealed before the membrane goes on; and the membrane must be turned up at every vertical face by the specified height (commonly 300 mm in toilets, more on terraces).",
    "Slopes: terraces typically 1:100 to 1:120 towards the outlet; toilet sunk slabs sloped to the trap; balconies sloped away from the room with a threshold or drip.",
    "Testing: ponding test for terraces and toilet sunks — fill with water to the specified depth and hold for 48 to 72 hours, with the underside inspected. A ponding test that has not been witnessed and signed did not happen.",
    "Protection: screed or protection layer over a membrane before any traffic, and the rule that no trade works on a waterproofed surface without protection in place.",
    "Documentation: the waterproofing agency's warranty, the applied system record, batch numbers of materials, the ponding test record, and photographs at each stage. This package is what protects the company in a dispute five years later.",
  ],
  do: [
    "Inspect a toilet sunk before waterproofing: slope, cleanliness, plumbing penetrations complete, corners filleted.",
    "Witness and record a ponding test end to end, including the underside inspection.",
    "Inspect a terrace membrane for laps, terminations, and turn-up height.",
    "Compile the waterproofing documentation package for one area.",
  ],
  drill: "Take one completed toilet. Trace the entire waterproofing history from the documentation — substrate approval, system applied, batch numbers, ponding test record, protection. Identify every gap in the record and report it.",
  mistakes: [
    "Ponding for 24 hours instead of the specified duration because the schedule is tight.",
    "Allowing tiling to start over a membrane that has no protection screed.",
    "Waterproofing before the plumbing penetrations are final, so the membrane is cut afterwards.",
    "Accepting a system substitution from the contractor without the consultant's written approval.",
  ],
  check: [
    "How long is a ponding test held and who must witness it?",
    "What is the minimum turn-up height for waterproofing on a toilet wall, and where is it specified?",
    "A terrace has ponding water three days after rain. What are the two most likely causes?",
  ],
},
{
  id: "M13", title: "Tiling & Flooring",
  days: "Supervision immersion",
  why: "Tiling is the finish a customer inspects most closely and complains about most often. It is also entirely dependent on the accuracy of everything done before it — levels, plaster, waterproofing and plumbing. Good tiling on a bad base is not possible.",
  know: [
    "Materials: vitrified tiles, ceramic tiles, glazed and unglazed, double-charge and full-body, natural stone (granite, marble, kota), and their acceptance parameters — dimensional tolerance, warpage, water absorption, shade and batch consistency.",
    "Shade and batch control: all tiles for one continuous area must be from one batch and one shade. Mixed batches are visible under grazing light and cannot be corrected.",
    "Substrate: level and cured, correct SFL allowing for tile plus adhesive thickness, waterproofing complete and protected, and all wet-area slopes established before tiling.",
    "Bedding: cement mortar bed versus tile adhesive. Adhesive is applied with a notched trowel and requires full contact — the back-buttering technique for large-format tiles. Full bedding, not dab-fixing on five points.",
    "Setting out: always dry-lay the layout first. Start from the most visible line, keep cut tiles at the least visible edge, align joints across doorways, and keep the joint width uniform with spacers.",
    "Wet areas: slope towards the floor trap (commonly 1:80 to 1:100), no ponding, and the floor level kept below the adjoining dry area with a threshold.",
    "Grouting: joints cleaned and grouted after the bed has set, epoxy grout in wet areas where specified, and cleaning before the grout hardens on the tile face.",
    "Quality checks: hollowness by tapping every tile, lippage between adjacent tiles against the specified limit, joint alignment along a string line, level across the room, slope confirmed by pouring water, and skirting alignment.",
    "Protection: covering finished floors before other trades work in the area. Damage to a finished floor by a following trade is a scheduling failure, not an accident.",
  ],
  do: [
    "Verify a tile consignment for shade, batch, dimensions and breakage, and record acceptance.",
    "Dry-lay and approve a tiling layout for one room before fixing starts.",
    "Inspect completed tiling: tap every tile, check lippage, joints, level and slope. Produce a snag list.",
    "Pour water in a finished toilet and confirm complete drainage with no ponding.",
  ],
  drill: "Inspect a fully tiled flat. Tap-test every tile and record the hollow percentage room by room. Check lippage at 20 random joints. Present the snag list with photographs and the acceptance decision.",
  mistakes: [
    "Dab-fixing large tiles on five mortar spots, which leaves them hollow and they crack under load within a year.",
    "Starting from a wall instead of dry-laying, which forces a sliver-width cut tile at the most visible edge.",
    "Tiling before the plumbing test is complete, so the floor is broken open a week later.",
    "Mixing two shade batches in one room.",
  ],
  check: [
    "Why must tiles be dry-laid before fixing?",
    "What slope is required in a toilet floor and how do you verify it after tiling?",
    "You find 8% of tiles hollow on tapping in a living room. What is your decision?",
  ],
},
{
  id: "M14", title: "Plumbing & Sanitary",
  days: "Supervision immersion",
  why: "Plumbing is concealed, pressurised and directly upstream of every water-damage complaint. A leak found before tiling costs a few hundred rupees. The same leak found after handover costs the flat's finishes, the flat below, and the customer's trust.",
  know: [
    "Systems and materials: water supply in CPVC or PPR (hot and cold) and UPVC or GI where specified; drainage and soil in PVC/UPVC; rainwater; firefighting in MS/GI; and the fittings, valves and jointing method appropriate to each.",
    "Reading a plumbing drawing: riser diagram, shaft layout, fixture positions, trap and floor drain locations, vent lines, and the coordination of sleeve positions with the structural drawing before the slab is cast.",
    "Sleeves and cutouts: every penetration must be sleeved or cast in, never cut afterwards. A core cut through a beam is a structural failure.",
    "Slopes for drainage: soil and waste lines laid to a continuous fall — commonly around 1:40 to 1:60 for 100 mm lines depending on the specification — with no back-fall, no sag, and rodding access at every change of direction.",
    "Traps and seals: every fixture trapped, a water seal typically 50 mm, and vent lines sized and connected so the seal is not siphoned out.",
    "Testing before concealment — the discipline that decides everything: water supply lines hydro-tested at the specified pressure (commonly 1.5 to 2 times working pressure, held for the specified duration, typically 24 hours) with a gauge fitted and the reading recorded and witnessed; drainage lines tested by water or smoke/ball test; and no chasing, plastering or tiling permitted over an untested line.",
    "Fixture installation: heights of taps, showers, WC, wash basin and floor traps against the standard schedule; alignment with tile joints; sealing at wall penetrations; and protection until handover.",
    "Water tanks, pumps and the hydro-pneumatic system: capacity, overflow and scour arrangements, level controls, and the sequence of commissioning.",
    "Documentation: the pressure test record with gauge reading, duration, date, witness signature and photograph. This is what you produce when a leak appears in year two.",
  ],
  do: [
    "Mark sleeve positions on a slab shutter from the plumbing drawing and get them verified before the pour.",
    "Witness and record a hydro test on a concealed water line, including the gauge photograph.",
    "Check drainage line slope with a level and confirm there is no back-fall.",
    "Inspect installed fixtures against the height schedule.",
  ],
  drill: "Take one flat's plumbing from the shaft to the fixtures. Confirm from records that every concealed line was tested and witnessed before concealment. Where the record is missing, raise it formally. Report the percentage of lines with complete records.",
  mistakes: [
    "Allowing plaster or tiling over an untested line because the finishing gang was ready.",
    "Testing at a pressure lower than specified, or for a shorter time, and recording it as passed.",
    "Cutting a beam or slab for a missed penetration instead of escalating it.",
    "Laying a drainage line to a slope that reverses over its length because it was set by eye.",
  ],
  check: [
    "At what pressure and for how long is a concealed water line tested on our sites, and who signs?",
    "What is a trap seal and what happens if the vent is missing?",
    "The tiling gang wants to start in a toilet where the hydro test record is missing. What do you do?",
  ],
},
{
  id: "M15", title: "Electrical",
  days: "Supervision immersion",
  why: "Electrical work is the trade with the highest life-safety consequence and the least visible workmanship. It is also the trade most often rushed at the end. Your job is to make sure the concealed work was right, because after handover nobody will ever see it again.",
  know: [
    "The distribution chain: incoming supply, transformer and HT/LT panel, main LT panel, risers, floor distribution boards, flat DBs, and final circuits. Understand where the load of your building is measured and how it is divided.",
    "Protection devices: MCB, MCCB, RCCB/RCBO, ELCB, and their ratings. Which circuits must be on an RCCB and why. Discrimination between upstream and downstream devices.",
    "Earthing: the earth pit construction, earth electrode, earth strip runs, earth continuity to every metal enclosure, equipotential bonding in bathrooms, and earth resistance measurement — the acceptable value is specified by the consultant and the applicable code.",
    "Concealed conduiting: conduit laid in the slab before the pour, fixed against displacement, with pull wires; junction and switch boxes positioned and levelled; chases cut to the correct depth and made good; and the ban on cutting reinforcement for conduit routing.",
    "Wiring: cable sizes against circuit load and length, colour code for phase, neutral and earth, loop-in system at switch boxes, no joints inside conduit, and the number of wires permitted in a conduit.",
    "Testing before handover: insulation resistance by megger (the accepted minimum for a low-voltage installation is commonly 1 MΩ — confirm against IS 732 and the consultant's specification), earth continuity, earth resistance, polarity check, and the phase balance of the DB.",
    "Fixture and accessory installation: heights of switches and sockets against the schedule, alignment with tile joints, plate levelling, and labelling of the DB.",
    "Coordination: the electrical layout must be reconciled against tiling layout, false ceiling layout, kitchen and wardrobe drawings before conduiting, not after.",
    "Commissioning and statutory: load sanction, electrical inspector approval where applicable, DG set and its earthing and exhaust, lift power supply, and firefighting system power.",
  ],
  do: [
    "Check slab conduiting before a pour: routing, fixing, boxes, pull wires, and no reinforcement disturbed.",
    "Witness and record a megger test on one flat and interpret the reading.",
    "Inspect an earth pit and record the earth resistance measurement.",
    "Check switch and socket heights and alignment against the schedule and the tile joints in one flat.",
  ],
  drill: "Take one flat. Overlay the electrical points on the tiling layout and the false ceiling layout. Report every point that will land on a tile joint, behind a wardrobe, or inside a ceiling drop. Do this before conduiting on the next flat and record the saving.",
  mistakes: [
    "Allowing a conduit to be routed by cutting reinforcement.",
    "Accepting a megger reading without recording the instrument, the circuit, the value and the witness.",
    "Fixing switch boxes without reference to the tile layout, so the plate straddles a joint.",
    "Leaving joints inside a conduit — legal to nobody, invisible to everybody, and a fire risk forever.",
  ],
  check: [
    "What is the minimum acceptable insulation resistance and where is it specified?",
    "Which circuits in a flat must be protected by an RCCB and why?",
    "An electrician has cut a slab bar to route a conduit. What is your immediate action and what document do you raise?",
  ],
},
{
  id: "M16", title: "Stores & Inventory Management",
  days: "D09 and the Store immersion",
  why: "Between 55% and 70% of a project's cost passes through the store. A store that is not controlled is not a store, it is a leak. Every trainee at Neoteric spends time in the store because material discipline is the fastest way to understand where money actually goes.",
  know: [
    "The procurement cycle end to end: indent raised by site, approval, purchase requisition, comparative statement, purchase order, delivery, GRN, quality acceptance, storage, issue against MRN, consumption booking, and reconciliation.",
    "Documents and what each one proves: Indent (what site needs), PO (what was agreed and at what rate), Delivery Challan (what the vendor says he sent), GRN/Goods Receipt Note (what we actually received and accepted), MRN/Material Requisition Note (what we issued and to whom), Material Transfer Note (movement between sites), and the Debit Note (what we are charging back).",
    "Gate discipline: every vehicle logged in and out, weighbridge slip where applicable, quantity counted and recorded independently of the challan, quality checked against the specification, and short or damaged supply recorded on the challan before signing.",
    "Storage: dedicated bins and locations, material identification tags, FIFO enforcement, weather protection, segregation of hazardous and flammable material, fire extinguishers, and separation of accepted, quarantined and rejected material.",
    "Issue control: no issue without an approved MRN, issue against the executing agency and the work item, and daily posting so the stock ledger is never more than 24 hours out of date.",
    "Reconciliation: theoretical consumption from executed quantity versus actual issue, item by item, monthly. This is the single most powerful control on a construction site, and the one most often skipped.",
    "Wastage norms: acceptable percentages for cement, steel, tiles, bricks and paint, and what triggers an investigation.",
    "Contractor-supplied versus company-supplied material, and the recovery mechanism when a contractor consumes more than the norm.",
    "Scrap and returns: scrap steel, empty cement bags, damaged material, and the fact that scrap is an asset with a sale value and a theft risk.",
    "Neoteric's Store Management System: the digital workflow, roles, and how the physical process maps to the screens.",
  ],
  do: [
    "Receive a consignment end to end: gate entry, count, quality check, GRN, and put-away with tagging.",
    "Process an MRN and post it to the stock ledger.",
    "Conduct a physical stock count of ten items and reconcile against the ledger, explaining every variance.",
    "Prepare a monthly reconciliation for cement and steel for one building.",
  ],
  drill: "Do a surprise physical verification of the five highest-value items in the store. Reconcile against the system stock. For every variance, trace the transaction history and identify the cause. Present to the Training Coordinator with a control recommendation.",
  mistakes: [
    "Signing a delivery challan before counting, on the promise that the count will be done later.",
    "Issuing material on a verbal request from a senior. If it is not on an MRN, it did not happen.",
    "Recording GRN quantity from the challan rather than from your own count.",
    "Letting the stock ledger fall behind, at which point reconciliation becomes impossible and everyone stops trying.",
  ],
  check: [
    "What is the difference between a Delivery Challan and a GRN, and which one protects the company?",
    "A vendor delivers 480 bags against a PO for 500 and the driver is in a hurry. Exactly what do you write and where?",
    "What does a 9% negative variance in cement reconciliation tell you, and what are the three possible causes?",
  ],
},
{
  id: "M17", title: "Estimation, BOQ & Rate Analysis",
  days: "D10 and the Measurement immersion",
  why: "Estimation is how the company decides whether a project is worth building and what it can afford to pay. As a site engineer you will not prepare the master estimate, but you will be asked constantly whether something is within budget, what a variation costs, and whether a contractor's claim is reasonable. You cannot answer any of those without understanding how the number was built.",
  know: [
    "Types of estimate and their accuracy: plinth area rate estimate, detailed estimate, and the revised estimate. When each is used and what it can and cannot be relied upon for.",
    "The Bill of Quantities: item code, description, unit, quantity, rate, amount. How the item description defines exactly what is included — and therefore what is a variation.",
    "Taking off quantities: the systematic sequence (substructure, superstructure, finishes, services, external), the take-off sheet, and the discipline of a traceable calculation that another person can check.",
    "Centre-line method and long-wall short-wall method for masonry and foundation quantities, and when each is quicker.",
    "Rate analysis: how a rate is built from material, labour, plant, overheads and profit. The material component with wastage, the labour component with output norms, and the contractor's margin. Understanding this is what lets you argue a rate rather than accept one.",
    "Standard references: the CPWD/PWD Schedule of Rates for the state, DSR item descriptions, and market rate discovery for items not in the schedule.",
    "Escalation and price variation clauses, and how a change in steel or cement price flows into the contract.",
    "Variations and extra items: what constitutes a variation, how the rate for a new item is derived from the contract, and why every variation must be approved in writing before execution.",
    "Budget versus actual: how the site's executed quantity is tracked against the BOQ quantity, and the early warning that a quantity overrun gives you.",
  ],
  do: [
    "Take off the quantities for one flat's masonry, plaster and tiling from the drawings and compare against the BOQ.",
    "Build a rate analysis for one item from first principles and compare it against the contracted rate.",
    "Identify a variation on site, price it, and prepare the note seeking approval.",
    "Prepare a BOQ quantity versus executed quantity statement for one building and flag the overruns.",
  ],
  drill: "Pick one BOQ item where the executed quantity is running ahead of the tendered quantity. Trace why — drawing change, take-off error, wastage, or scope creep. Present the root cause and the financial impact.",
  mistakes: [
    "Quoting a number from memory when asked 'roughly what will this cost'. Say you will check and then check.",
    "Allowing a contractor to start an extra item on a verbal assurance that the rate will be settled later.",
    "Taking off from an old drawing revision.",
    "Treating the BOQ description as decoration. The description is the contract.",
  ],
  check: [
    "What are the five components of a rate, and which one do you have the most control over on site?",
    "A contractor claims an item is extra. How do you determine whether it is?",
    "Executed masonry is 18% above the BOQ quantity for a floor. Name three possible causes.",
  ],
},
{
  id: "M18", title: "Quantity Surveying & Contractor Billing",
  days: "Measurement immersion",
  why: "Certifying a bill is the moment when everything you have measured, inspected and recorded turns into money leaving the company. It is the highest-trust activity a junior engineer performs, and the one where a lack of rigour is most expensive and most permanent.",
  know: [
    "The Running Account (RA) bill cycle: contractor submits, site measures jointly, quantities certified, deductions applied, bill checked by QS/Accounts, certified for payment, paid, and the cumulative record carried to the next bill.",
    "Joint measurement: measured by the contractor's representative and the company's engineer together, recorded in the MB, and signed by both. A quantity that is not jointly measured is a future dispute.",
    "Deductions and recoveries in a bill: retention/security deposit, mobilisation advance recovery, material advance recovery, material issued at company cost and recovered at the contract rate, penalty or liquidated damages, TDS, GST treatment, labour cess, and debit notes for damage or rectification.",
    "The cumulative principle: an RA bill always shows quantity up to date, quantity paid previously, and quantity payable now. Errors compound across bills, which is why every bill must be checked against the previous certified position, not started fresh.",
    "Rate application: the contracted rate only, the correct item code, and no rate applied to an item that is not in the contract without an approved variation.",
    "Quality gating on payment: work that has an open NCR is not certified. This is the strongest quality lever the company has and it is only effective if it is used consistently.",
    "The final bill: no-claim certificate, defect liability period, release of retention, and the closure documentation.",
    "Sub-contractor and labour payment discipline, and the company's exposure if a contractor does not pay his workers.",
    "The quarterly performance incentive and penalty mechanism used in Neoteric's construction contracts, and how the site's records feed it.",
  ],
  do: [
    "Carry out a joint measurement for one item with a contractor's representative and record it in the MB.",
    "Check an RA bill line by line against the MB, the previous bill and the contract rates, and list every discrepancy.",
    "Compute the deductions for one RA bill in full.",
    "Prepare a debit note for material consumed above the wastage norm.",
  ],
  drill: "Take a submitted RA bill that has not yet been certified. Check it independently before the QS does. Present your findings alongside the QS's findings and account for every difference between the two.",
  mistakes: [
    "Certifying on the contractor's measurement sheet because it 'looks about right'.",
    "Missing a recovery, which is almost never noticed until the final bill when the money is gone.",
    "Certifying work that has an open NCR because the contractor promised to fix it.",
    "Signing a bill without checking the previous cumulative quantity.",
  ],
  check: [
    "What does an RA bill show in its three quantity columns and why does that structure matter?",
    "List six deductions that may appear in an RA bill.",
    "A contractor's bill includes an item you cannot find in the contract. What do you do?",
  ],
},
{
  id: "M19", title: "Quality Control — Checklists, NCR & Stop-Work Authority",
  days: "D11 and the Quality immersion",
  why: "Neoteric operates a Stop-Work Authority and NCR system because we found engineers signing checklists for inspections they had not performed. You are joining a company that has already had that problem and has decided how it will be dealt with. Read this module as policy, not as theory.",
  know: [
    "The quality system: the project quality plan, the inspection and test plan (ITP) for each activity, the trade-wise QC checklists, the hold points at which work may not proceed without inspection, and the witness points.",
    "How a checklist works: it is signed by the person who physically performed the inspection, at the location, at the time. A checklist signed in the site office is a false document, and it is treated as one.",
    "Hold points you will encounter constantly: pre-pour inspection, reinforcement inspection, pre-plaster, pre-tiling, pre-concealment of services, pre-handover. Work that passes a hold point without inspection must be opened up or rejected.",
    "Non-Conformance Report (NCR): what triggers one, how it is raised, who it is issued to, the required response (correction, root cause, corrective action, preventive action), verification of closure, and the register that tracks open NCRs.",
    "Stop-Work Authority (SWA): every employee, including you on your first week, has the authority and the obligation to stop work that is unsafe or that will produce non-conforming permanent work. Nobody may be penalised for exercising SWA in good faith. Every SWA is logged, reviewed and closed.",
    "Escalation: what you decide yourself, what goes to the Site Engineer, what goes to the Project Manager, and what goes to the Head of Projects the same day.",
    "Snag and defect management: snag list generation, allocation, rectification, re-inspection and closure, with photographic evidence at each stage.",
    "Records: what the company must be able to produce three years from now to defend a quality claim, and why your daily discipline is what makes that possible.",
    "The integrity standard: a false record is a disciplinary matter, not a performance matter. This applies from Day 1 of your training.",
  ],
  do: [
    "Perform a pre-pour inspection using the checklist and sign it, having physically verified every line.",
    "Raise an NCR with a clear description, evidence, reference to the specification breached, and a required action.",
    "Exercise Stop-Work Authority in a live situation under supervision and complete the log.",
    "Produce a snag list for one flat and follow it through to closure.",
  ],
  drill: "Take ten closed checklists from the last month for a single activity. Physically verify what the checklist claims, where the work is still visible. Report any line item you cannot substantiate. This is the audit that the company will run on you later — learn it by running it yourself first.",
  mistakes: [
    "Signing a checklist to keep the pour on schedule. This ends careers here.",
    "Raising an NCR verbally. If it is not written and registered, it does not exist.",
    "Closing an NCR without verifying the corrective action physically.",
    "Not exercising SWA because you are junior. Seniority is not a requirement for SWA — that is the entire point of it.",
  ],
  check: [
    "Who at Neoteric has Stop-Work Authority?",
    "What are the mandatory contents of an NCR?",
    "A Project Manager asks you to sign the pre-pour checklist while he holds the reinforcement inspection for later. What is your answer?",
  ],
},
{
  id: "M20", title: "Site Documentation, Reporting & Digital Discipline",
  days: "Throughout",
  why: "The company can only manage what it can see. Your daily record is the raw material for every decision made above you — cash flow, procurement, contractor performance, and the CEO's monthly review. A site that reports badly gets managed badly, whatever its actual performance.",
  know: [
    "The Site Diary: a daily, contemporaneous, handwritten or digital record of weather, manpower by agency and trade, plant deployed, work executed by location, material received, instructions given and received, visitors, and any event that could later matter in a dispute. It is the single most useful document in construction litigation.",
    "The Daily Progress Report (DPR): what was planned, what was done, manpower deployed, quantities executed, constraints and delays with reasons, and tomorrow's plan. Submitted the same day, not the next morning.",
    "Weekly and monthly reporting: physical progress against schedule, S-curve, quantity executed against BOQ, material consumption and reconciliation, quality metrics (open NCRs, checklist compliance), safety metrics, and the look-ahead plan.",
    "Photographic documentation: dated, located, and filed by area and activity. Photographs before concealment are worth more than any certificate.",
    "Planning basics: the bar chart / Gantt schedule, the critical path in plain terms, the 3-week look-ahead, the constraint log, and how a delay in one trade propagates.",
    "Written communication: how to write a site instruction to a contractor, an escalation email to a senior, and a minutes-of-meeting record. Keep it short, dated, factual, and free of adjectives.",
    "Digital tools at Neoteric: the QC checklist application, the Store Management System, Slack channel structure and what is posted where, and the drawing register. Learn the tool, but understand the process first — a digital record of a fake inspection is still fake.",
    "Filing and retrieval: the test that matters is whether a colleague who was not there can find and understand your record two years later without asking you.",
  ],
  do: [
    "Maintain a complete Site Diary for a full week without a gap.",
    "Prepare and submit a DPR every working day of the programme.",
    "Write one site instruction to a contractor and one escalation note to the Project Manager.",
    "Produce a weekly progress report with an S-curve for the area you are attached to.",
  ],
  drill: "Take the site's DPRs for the last two weeks. Reconstruct what actually happened on site from the reports alone. Identify every day where the report does not let you do this, and what was missing.",
  mistakes: [
    "Writing the diary at the end of the week from memory.",
    "Reporting 'work in progress' without a quantity. A DPR without numbers is not a report.",
    "Recording a delay without recording its cause and who was informed.",
    "Long emails. A senior reading twenty reports will read your first three lines.",
  ],
  check: [
    "What are the mandatory contents of a Site Diary entry?",
    "Why is a photograph before concealment more valuable than a signed certificate?",
    "Write a three-line escalation note about a contractor who has not mobilised as committed.",
  ],
},
{
  id: "M21", title: "Labour, Contractor & Site Management",
  days: "Throughout, formally in the Supervision immersion",
  why: "You will be responsible for output produced by people who do not report to you, who often have more site experience than you, and who are paid by someone else. Technical knowledge alone will not get work out of them. This is the module that decides whether you become an engineer or a supervisor.",
  know: [
    "Who is who on site: the main contractor, sub-contractors, the petty contractor, the mistri, the gang leader, skilled and unskilled labour, and where each one's incentive actually lies.",
    "Productivity norms: how much a mason lays in a day, how much plaster a gang completes, how many square metres of tiling per day. Knowing the norm is what lets you plan manpower and challenge a contractor's excuse.",
    "Daily manpower planning: computing required manpower from the target quantity and the norm, checking actual deployment at muster, and raising a shortfall the same morning rather than at the end of the week.",
    "Instructing effectively: instruct the gang leader, not individual workers; be specific about location, quantity and finish; confirm understanding by asking the instruction to be repeated back; and follow up at the midpoint, not at the end.",
    "Statutory and welfare basics: labour licence, contractor registration, wage register, attendance, PF/ESI applicability, minimum wage, working hours, restrictions on employment, drinking water, toilets, and rest shelter. A site that fails on welfare will fail on quality too.",
    "Labour camp and site facilities: hygiene, safety, and the fact that the condition of the camp is a leading indicator of the contractor's overall discipline.",
    "Handling conflict: disputes over measurement, allegations of favouritism, wage disputes, and the rule that you never negotiate a wage or a rate directly with a worker.",
    "Working with people senior to you in age and experience: authority on a construction site comes from being consistently right and consistently fair, not from your designation. Ask, verify, then instruct.",
  ],
  do: [
    "Compute the manpower required for a target and check the actual muster against it.",
    "Give a work instruction to a gang leader and verify it was executed as instructed.",
    "Audit a labour camp and welfare facilities against the checklist.",
    "Handle one measurement disagreement with a contractor to a documented resolution.",
  ],
  drill: "For one week, record the planned manpower, the actual manpower and the actual output for one trade. At the end of the week, present the productivity achieved against the norm and your explanation for the gap.",
  mistakes: [
    "Shouting. It works once and never again, and it costs you the gang leader.",
    "Instructing an individual worker directly, which undermines the gang leader you actually depend on.",
    "Accepting 'labour problem' as a reason. Ask which trade, how many short, since when, and what the contractor has done about it.",
    "Making a commitment on payment or rate. That is not your authority, ever.",
  ],
  check: [
    "How many square metres of internal plaster should a gang of one mason and two helpers complete in a day, and where did you get that number?",
    "A contractor says he is short of manpower because of a festival. What are the four questions you ask?",
    "A worker complains directly to you about his wages. What do you do?",
  ],
},
{
  id: "M22", title: "Snagging, Handover & Customer Quality",
  days: "Quality immersion",
  why: "The customer does not experience your cube results. They experience a door that sticks, a tap that drips and a tile that sounds hollow. Handover quality is where all the invisible work of the previous two years becomes visible, and where a company's reputation is actually made.",
  know: [
    "The de-snagging sequence: internal snagging by the site team, rectification, re-inspection, snagging by the quality team, rectification, and only then the customer walkthrough.",
    "What a snag list is: room by room, element by element, with a defect description, a photograph, a responsible agency, a target date and a closure signature. Not a list of complaints in a notebook.",
    "The high-frequency snags in residential handover, in order: hollow tiles, plaster cracks at RCC-masonry junctions, door and window operation and alignment, paint finish and patching, plumbing leaks and slow drainage, electrical points not working or wrongly located, water ponding in balconies and terraces, and cleaning.",
    "Pre-handover testing: full water flow and drainage test in every wet area, every electrical point energised and tested, every door and window operated, every lock and handle checked, and the flat cleaned to handover standard.",
    "The handover documentation package: completion certificate, as-built drawings, warranties for waterproofing, lift, pumps and fixtures, the operation and maintenance manual, key handover record and the customer acknowledgement.",
    "The defect liability period: what is covered, what is not, how a customer complaint is logged and resolved, and the turnaround standard.",
    "The economics: a snag rectified before handover costs a fraction of the same snag rectified after, because after handover it also costs access, protection, customer time, and goodwill.",
    "Your role: as a trainee you will do more snagging than anyone. Snagging is the fastest way to learn what good workmanship looks like, because you are being paid to find every place it is absent.",
  ],
  do: [
    "Produce a complete room-by-room snag list for one flat with photographs.",
    "Follow one snag list through rectification to verified closure.",
    "Conduct a full pre-handover functional test of one flat.",
    "Assemble the handover documentation package for one unit and identify what is missing.",
  ],
  drill: "Snag one flat completely and independently. Then walk the same flat with the Quality Head. Every snag he finds that you missed is a gap in your standard — write each one down and carry the list for the rest of your career.",
  mistakes: [
    "Snagging with the contractor present, which turns an inspection into a negotiation.",
    "Closing a snag on the contractor's word rather than on re-inspection.",
    "Snagging only what is at eye level. Look up, look down, open everything, run every tap.",
    "Handing over a flat with an open snag on the promise that it will be fixed next week.",
  ],
  check: [
    "List the five most common snags in a residential flat and their upstream causes.",
    "Why is the customer walkthrough the third inspection, not the first?",
    "A flat has one open snag and the customer is waiting. What is your recommendation and to whom?",
  ],
},
];
